CC=cc
CFLAGS=-g
FILES=../fifo.c

all: oneadd multipleadd types

clean:
	rm oneadd multipleadd types

oneadd:
	$(CC) $(CFLAGS) oneadd.c $(FILES) -o oneadd 

types:
	$(CC) $(CFLAGS) types.c $(FILES) -o types

multipleadd:
	$(CC) $(CFLAGS) multipleadd.c $(FILES) -o multipleadd

